[build]
publish = "public"
command = "git submodule update --init --recursive && bash scripts/tweego_build.sh && hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.81.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "git submodule update --init --recursive && bash scripts/tweego_build.sh && hugo -D -F -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.81.0"

[context.branch-deploy]
command = "git submodule update --init --recursive && bash scripts/tweego_build.sh && hugo -D -F -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.81.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]

from = "/docs/glossaries/contributing/roadmap"
to = "/docs/glossaries/roadmap/"
[[redirects]]

from = "/docs/glossaries/primer/maturity-levels"
to = "/docs/glossaries/maturity-levels/"

[[redirects]]
from = "/licences"
to = "/licenses/"
